name: Docker Subir al Servidor de Docker Hub

on:
  push:
    branches:
      - pablo
      - carla
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Iniciar sesión en Docker Hub
        run: echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "carla123" --password-stdin  # Aquí pones directamente el nombre de usuario

      - name: Construir la imagen Docker
        run: docker build -t gg-gamers:latest .

      - name: Etiquetar la imagen para Docker Hub
        run: docker tag gg-gamers:latest carla123/gg-gamers:latest  # Aquí también pones el nombre de usuario

      - name: Subir imagen a Docker Hub
        run: docker push carla123/gg-gamers:latest  # Y también aquí
