name: Notify DailyBot on PR

on:
  pull_request:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send PR message to DailyBot
        run: |
          curl -X POST ${{ secrets.GOOGLE_CHAT_WEBHOOK }} \
            -H 'Content-Type: application/json' \
            -d '{
              "text": "📢 Nuevo Pull Request: \"${{ github.event.pull_request.title }}\" creado por ${{ github.actor }}\n🔗 ${{ github.event.pull_request.html_url }}"
            }'
